### ISSUE TITLE
Project plan document

### ISSUE THREAD

**Issue by joonaruutiainen** [joonaruutiainen/interactive-process-graphs#1]
**Description.**
Project plan document version 1.0.

**Definition of Done**
All required sections of the document done. All group members must be familiar with the project plan and agree to it.

**Time estimate**
7h (working together as a group)

**Checklist**
- [x] Go through all document sections and write necessary information
- [x] Verify and accept the plan as a group
- [x] Submit the project plan document to Moodle

**Additional notes and assumptions**
-
